-- 7.6.1
-- 問題: 1 --
-- (A) 単一行副問い合わせ
-- (B) select
-- (C) set
-- (D) 複数
-- (E) 1
-- (F) 複数行副問い合わせ
-- (G) any, in, all
-- (H) (G)に含まれない右のものany, in, all
-- (I) from
-- (J) 表
-- (K) insert

-- 模範解答:1
-- (A)単一行副問い合わせ
-- (B)SELECT
-- (C)SET
-- (D)n
-- (E)1
-- (F)複数行副問い合わせ
-- (G)IN　または　NOT IN　または　ANY　または　ALL　※(H)と異なる語句であること
-- (H)IN　または　NOT IN　または　ANY　または　ALL　※(G)と異なる語句であること
-- (I)FROM
-- (J)表
-- (K)INSERT